# Generated by Django 6.0.2 on 2026-02-26 23:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inbox', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(verbose_name='Şirkət məlumatları')),
            ],
            options={
                'verbose_name': 'Şirkət məlumatı',
                'verbose_name_plural': 'Şirkət məlumatları',
            },
        ),
    ]
