# Generated by Django 6.0.2 on 2026-02-26 23:38

import django_ckeditor_5.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inbox', '0002_companyinfo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companyinfo',
            name='content',
            field=django_ckeditor_5.fields.CKEditor5Field(verbose_name='Şirkət məlumatları'),
        ),
    ]
